name: Continuous Integration


on:
  push:
    branches:
      - 'main'

jobs:
  unit_testing:
    strategy:
      fail-fast: false #makes sure all tests run even if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    
    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #action created by Github

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install pytest
        run: pip install pytest #Only one dependency, so no need for a venv or requirements.txt file

      - name: Run tests
        run: pytest tests